# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20161122_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Test',
        ),
    ]
