# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20161126_0508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Text',
        ),
    ]
